name: DOT-Test-VR

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Instalar Xvfb
        run: sudo apt-get install -y xvfb

      - name: Instalar Firefox (caso deseje usar)
        run: sudo apt-get install -y firefox

      - name: Definir variável de ambiente TERM
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Executar Cypress com Xvfb no Chrome (caso o Firefox tenha problemas)
        run: |
          xvfb-run --server-args='-screen 0 1280x1024x24' npx cypress run --headless --browser chrome --spec 'cypress/e2e/**/*.cy.js'
