name: DOT-Test-VR

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Definir variável de ambiente TERM
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Executar testes Cypress
        run: npx cypress run --headless --spec 'cypress/e2e/**/*.cy.js'
